server:
  port: 1122
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          #远程仓库https地址
          uri: https://gitee.com/zhang-songyao/spring-cloud.git