server:
  port: 9527
spring:
  application:
    name: springcloud-zuul-demo
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 采用IP注册
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*" # 不能再使用这个路径访问了  ignored: 忽略，隐藏全部的
  prefix: /dunkcode   # 添加统一的访问前缀
