server:
  port: 8001


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
 # config-location: classpath:mybatis/mybaits-config.xml
  configuration:
    #下划线转为大写
    map-underscore-to-camel-case: true


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_01?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 333


# Eureka配置 服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    # 采用IP注册
    prefer-ip-address: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
